using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace AionBot
{
    partial class fBot
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        // Fields
        private TextBox afterDeathDelay;
        private TextBox afterDeathSeq;
        private BackgroundWorker backgroundWorker1;
        private BackgroundWorker backgroundWorker2;
        private Button button1;
        private Button button2;
        private Button button3;
        private Button button4;
        private Button button5;
        private Button button6;
        public int count = 0;
        private TextBox death_file_name;
        private TextBox fight_file_name;
        private TextBox fight1Delay;
        private TextBox fight2Delay;
        public int fightCount = 0;
        private TextBox fightSeq1;
        private TextBox fightSeq2;
        private TextBox healDelay;
        private TextBox healSeq;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private ToolStripMenuItem loadProfileToolStripMenuItem;
        private TextBox lootKey;
        private MenuStrip menuStrip1;
        private TextBox minHealth;
        public string msg = "";
        private TextBox pullDelay;
        private TextBox pullSeq;
        private TextBox record_file_name;
        private TextBox restKey;
        private ToolStripMenuItem saveProfileToolStripMenuItem;
        private TabControl tabControl1;
        private TabPage tabPage1;
        private TabPage tabPage2;
        private TextBox textBox1;
        public int timer = 0;
        private Timer timer1;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new Container();
            this.tabControl1 = new TabControl();
            this.tabPage1 = new TabPage();
            this.button5 = new Button();
            this.label17 = new Label();
            this.restKey = new TextBox();
            this.label16 = new Label();
            this.pullDelay = new TextBox();
            this.label15 = new Label();
            this.pullSeq = new TextBox();
            this.label14 = new Label();
            this.label13 = new Label();
            this.lootKey = new TextBox();
            this.label12 = new Label();
            this.minHealth = new TextBox();
            this.button3 = new Button();
            this.button4 = new Button();
            this.label9 = new Label();
            this.healDelay = new TextBox();
            this.label11 = new Label();
            this.healSeq = new TextBox();
            this.button2 = new Button();
            this.button1 = new Button();
            this.label7 = new Label();
            this.record_file_name = new TextBox();
            this.label8 = new Label();
            this.afterDeathDelay = new TextBox();
            this.label10 = new Label();
            this.afterDeathSeq = new TextBox();
            this.label5 = new Label();
            this.label6 = new Label();
            this.fight2Delay = new TextBox();
            this.fight1Delay = new TextBox();
            this.label3 = new Label();
            this.label4 = new Label();
            this.death_file_name = new TextBox();
            this.fight_file_name = new TextBox();
            this.label2 = new Label();
            this.label1 = new Label();
            this.fightSeq2 = new TextBox();
            this.fightSeq1 = new TextBox();
            this.menuStrip1 = new MenuStrip();
            this.saveProfileToolStripMenuItem = new ToolStripMenuItem();
            this.loadProfileToolStripMenuItem = new ToolStripMenuItem();
            this.tabPage2 = new TabPage();
            this.button6 = new Button();
            this.textBox1 = new TextBox();
            this.backgroundWorker1 = new BackgroundWorker();
            this.backgroundWorker2 = new BackgroundWorker();
            this.timer1 = new Timer(this.components);
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            base.SuspendLayout();
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Location = new Point(1, 2);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x204, 0xf9);
            this.tabControl1.TabIndex = 0;
            this.tabPage1.BackColor = Color.DarkGray;
            this.tabPage1.Controls.Add(this.button5);
            this.tabPage1.Controls.Add(this.label17);
            this.tabPage1.Controls.Add(this.restKey);
            this.tabPage1.Controls.Add(this.label16);
            this.tabPage1.Controls.Add(this.pullDelay);
            this.tabPage1.Controls.Add(this.label15);
            this.tabPage1.Controls.Add(this.pullSeq);
            this.tabPage1.Controls.Add(this.label14);
            this.tabPage1.Controls.Add(this.label13);
            this.tabPage1.Controls.Add(this.lootKey);
            this.tabPage1.Controls.Add(this.label12);
            this.tabPage1.Controls.Add(this.minHealth);
            this.tabPage1.Controls.Add(this.button3);
            this.tabPage1.Controls.Add(this.button4);
            this.tabPage1.Controls.Add(this.label9);
            this.tabPage1.Controls.Add(this.healDelay);
            this.tabPage1.Controls.Add(this.label11);
            this.tabPage1.Controls.Add(this.healSeq);
            this.tabPage1.Controls.Add(this.button2);
            this.tabPage1.Controls.Add(this.button1);
            this.tabPage1.Controls.Add(this.label7);
            this.tabPage1.Controls.Add(this.record_file_name);
            this.tabPage1.Controls.Add(this.label8);
            this.tabPage1.Controls.Add(this.afterDeathDelay);
            this.tabPage1.Controls.Add(this.label10);
            this.tabPage1.Controls.Add(this.afterDeathSeq);
            this.tabPage1.Controls.Add(this.label5);
            this.tabPage1.Controls.Add(this.label6);
            this.tabPage1.Controls.Add(this.fight2Delay);
            this.tabPage1.Controls.Add(this.fight1Delay);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Controls.Add(this.label4);
            this.tabPage1.Controls.Add(this.death_file_name);
            this.tabPage1.Controls.Add(this.fight_file_name);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this.fightSeq2);
            this.tabPage1.Controls.Add(this.fightSeq1);
            this.tabPage1.Controls.Add(this.menuStrip1);
            this.tabPage1.Location = new Point(4, 0x16);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(0x1fc, 0xdf);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Warrior";
            this.button5.Location = new Point(0xaf, 200);
            this.button5.Name = "button5";
            this.button5.Size = new Size(0x4b, 0x17);
            this.button5.TabIndex = 0x27;
            this.button5.Text = "Test Path";
            this.button5.UseVisualStyleBackColor = true;
            this.button5.Click += new EventHandler(this.button5_Click);
            this.label17.AutoSize = true;
            this.label17.Location = new Point(0xfd, 0x74);
            this.label17.Name = "label17";
            this.label17.Size = new Size(50, 13);
            this.label17.TabIndex = 0x25;
            this.label17.Text = "Rest Key";
            this.restKey.Location = new Point(0x100, 0x81);
            this.restKey.Name = "restKey";
            this.restKey.Size = new Size(0x3f, 20);
            this.restKey.TabIndex = 10;
            this.label16.AutoSize = true;
            this.label16.Location = new Point(190, 0x23);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x25, 13);
            this.label16.TabIndex = 0x23;
            this.label16.Text = "Delay ";
            this.pullDelay.Location = new Point(0xbb, 0x33);
            this.pullDelay.Name = "pullDelay";
            this.pullDelay.Size = new Size(0x3f, 20);
            this.pullDelay.TabIndex = 1;
            this.label15.AutoSize = true;
            this.label15.Location = new Point(7, 0x23);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x4c, 13);
            this.label15.TabIndex = 0x21;
            this.label15.Text = "Pull Sequence";
            this.pullSeq.Location = new Point(7, 0x33);
            this.pullSeq.Name = "pullSeq";
            this.pullSeq.Size = new Size(0xb1, 20);
            this.pullSeq.TabIndex = 0;
            this.label14.Location = new Point(0x14c, 0xc5);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x72, 0x15);
            this.label14.TabIndex = 0x1f;
            this.label14.Click += new EventHandler(this.label14_Click);
            this.label13.AutoSize = true;
            this.label13.Location = new Point(0x100, 0x26);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x31, 13);
            this.label13.TabIndex = 30;
            this.label13.Text = "Loot Key";
            this.lootKey.Location = new Point(0x100, 0x33);
            this.lootKey.Name = "lootKey";
            this.lootKey.Size = new Size(0x3f, 20);
            this.lootKey.TabIndex = 8;
            this.label12.AutoSize = true;
            this.label12.Location = new Point(0xfd, 0x4d);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x3a, 13);
            this.label12.TabIndex = 0x1c;
            this.label12.Text = "Min Health";
            this.minHealth.Location = new Point(0x100, 0x5d);
            this.minHealth.Name = "minHealth";
            this.minHealth.Size = new Size(0x3f, 20);
            this.minHealth.TabIndex = 9;
            this.button3.Location = new Point(0x55, 200);
            this.button3.Name = "button3";
            this.button3.Size = new Size(0x4b, 0x17);
            this.button3.TabIndex = 0x10;
            this.button3.Text = "Abort ";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new EventHandler(this.button3_Click);
            this.button4.Location = new Point(4, 200);
            this.button4.Name = "button4";
            this.button4.Size = new Size(0x4b, 0x17);
            this.button4.TabIndex = 15;
            this.button4.Text = "Run Bot";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new EventHandler(this.button4_Click);
            this.label9.AutoSize = true;
            this.label9.Location = new Point(0xb8, 0x9e);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x22, 13);
            this.label9.TabIndex = 0x18;
            this.label9.Text = "Delay";
            this.healDelay.Location = new Point(0xbb, 0xae);
            this.healDelay.Name = "healDelay";
            this.healDelay.Size = new Size(0x3f, 20);
            this.healDelay.TabIndex = 7;
            this.label11.AutoSize = true;
            this.label11.Location = new Point(7, 0xa1);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x81, 13);
            this.label11.TabIndex = 0x16;
            this.label11.Text = "Heal Self/Rest Sequence";
            this.healSeq.Location = new Point(7, 0xae);
            this.healSeq.Name = "healSeq";
            this.healSeq.Size = new Size(0xb1, 20);
            this.healSeq.TabIndex = 6;
            this.button2.Location = new Point(0xfb, 200);
            this.button2.Name = "button2";
            this.button2.Size = new Size(0x4b, 0x17);
            this.button2.TabIndex = 20;
            this.button2.Text = "Abort ";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new EventHandler(this.button2_Click);
            this.button1.Location = new Point(0xfb, 0xae);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x4b, 0x17);
            this.button1.TabIndex = 0x13;
            this.button1.Text = "Record Path";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(0x146, 0x9e);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x57, 13);
            this.label7.TabIndex = 0x12;
            this.label7.Text = "Record file name";
            this.label7.Click += new EventHandler(this.label7_Click);
            this.record_file_name.Location = new Point(0x149, 0xae);
            this.record_file_name.Name = "record_file_name";
            this.record_file_name.Size = new Size(0x91, 20);
            this.record_file_name.TabIndex = 0x11;
            this.record_file_name.Text = "deathmarch.txt";
            this.record_file_name.TextChanged += new EventHandler(this.textBox9_TextChanged);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(0x1c6, 0x71);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x25, 13);
            this.label8.TabIndex = 0x10;
            this.label8.Text = "Delay ";
            this.afterDeathDelay.Location = new Point(0x1c6, 0x81);
            this.afterDeathDelay.Name = "afterDeathDelay";
            this.afterDeathDelay.Size = new Size(50, 20);
            this.afterDeathDelay.TabIndex = 14;
            this.label10.AutoSize = true;
            this.label10.Location = new Point(0x146, 0x73);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x6f, 13);
            this.label10.TabIndex = 13;
            this.label10.Text = "After Death sequence";
            this.afterDeathSeq.Location = new Point(0x145, 0x81);
            this.afterDeathSeq.Name = "afterDeathSeq";
            this.afterDeathSeq.Size = new Size(0x7b, 20);
            this.afterDeathSeq.TabIndex = 13;
            this.label5.AutoSize = true;
            this.label5.Location = new Point(0x95, 0x71);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x65, 13);
            this.label5.TabIndex = 11;
            this.label5.Text = "Delay Between Seq";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(0xb8, 0x4d);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x25, 13);
            this.label6.TabIndex = 10;
            this.label6.Text = "Delay ";
            this.fight2Delay.Location = new Point(0xbb, 0x81);
            this.fight2Delay.Name = "fight2Delay";
            this.fight2Delay.Size = new Size(0x3f, 20);
            this.fight2Delay.TabIndex = 5;
            this.fight1Delay.Location = new Point(0xbb, 0x5d);
            this.fight1Delay.Name = "fight1Delay";
            this.fight1Delay.Size = new Size(0x3f, 20);
            this.fight1Delay.TabIndex = 3;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(0x145, 0x23);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x39, 13);
            this.label3.TabIndex = 7;
            this.label3.Text = "Resolution";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(0x142, 0x4c);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x63, 13);
            this.label4.TabIndex = 6;
            this.label4.Text = "After death path file";
            this.death_file_name.Location = new Point(0x145, 0x5c);
            this.death_file_name.Name = "death_file_name";
            this.death_file_name.Size = new Size(0x7b, 20);
            this.death_file_name.TabIndex = 12;
            this.fight_file_name.Location = new Point(0x144, 0x33);
            this.fight_file_name.Name = "fight_file_name";
            this.fight_file_name.Size = new Size(0x61, 20);
            this.fight_file_name.TabIndex = 11;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(7, 0x74);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x5b, 13);
            this.label2.TabIndex = 3;
            this.label2.Text = "Fight Sequence 2";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(7, 0x4d);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x5b, 13);
            this.label1.TabIndex = 2;
            this.label1.Text = "Fight Sequence 1";
            this.fightSeq2.Location = new Point(7, 0x81);
            this.fightSeq2.Name = "fightSeq2";
            this.fightSeq2.Size = new Size(0xb1, 20);
            this.fightSeq2.TabIndex = 4;
            this.fightSeq1.Location = new Point(7, 0x5d);
            this.fightSeq1.Name = "fightSeq1";
            this.fightSeq1.Size = new Size(0xb1, 20);
            this.fightSeq1.TabIndex = 2;
            this.fightSeq1.TextChanged += new EventHandler(this.textBox1_TextChanged);
            this.menuStrip1.Items.AddRange(new ToolStripItem[] { this.saveProfileToolStripMenuItem, this.loadProfileToolStripMenuItem });
            this.menuStrip1.Location = new Point(3, 3);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new Size(0x1f6, 0x18);
            this.menuStrip1.TabIndex = 0x26;
            this.menuStrip1.Text = "menuStrip1";
            this.saveProfileToolStripMenuItem.Name = "saveProfileToolStripMenuItem";
            this.saveProfileToolStripMenuItem.Size = new Size(80, 20);
            this.saveProfileToolStripMenuItem.Text = "Save Profile";
            this.saveProfileToolStripMenuItem.Click += new EventHandler(this.saveProfileToolStripMenuItem_Click);
            this.loadProfileToolStripMenuItem.Name = "loadProfileToolStripMenuItem";
            this.loadProfileToolStripMenuItem.Size = new Size(0x52, 20);
            this.loadProfileToolStripMenuItem.Text = "Load Profile";
            this.loadProfileToolStripMenuItem.Click += new EventHandler(this.loadProfileToolStripMenuItem_Click);
            this.tabPage2.Controls.Add(this.button6);
            this.tabPage2.Controls.Add(this.textBox1);
            this.tabPage2.Location = new Point(4, 0x16);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x228, 0xf6);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Healer";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.button6.Location = new Point(0xba, 0x7d);
            this.button6.Name = "button6";
            this.button6.Size = new Size(0x4b, 0x17);
            this.button6.TabIndex = 0x1b;
            this.button6.Text = "Test";
            this.button6.UseVisualStyleBackColor = true;
            this.button6.Click += new EventHandler(this.button6_Click);
            this.textBox1.Location = new Point(0xbd, 0x63);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(0xb1, 20);
            this.textBox1.TabIndex = 0x1a;
            this.backgroundWorker1.WorkerReportsProgress = true;
            this.backgroundWorker1.WorkerSupportsCancellation = true;
            this.backgroundWorker1.DoWork += new DoWorkEventHandler(this.backgroundWorker1_DoWork);
            this.backgroundWorker2.WorkerReportsProgress = true;
            this.backgroundWorker2.WorkerSupportsCancellation = true;
            this.backgroundWorker2.DoWork += new DoWorkEventHandler(this.backgroundWorker2_DoWork);
            this.timer1.Tick += new EventHandler(this.timer1_Tick);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.ClientSize = new Size(0x203, 250);
            base.Controls.Add(this.tabControl1);
            base.MainMenuStrip = this.menuStrip1;
            base.Name = "Form1";
            this.Text = "Aion";
            base.TopMost = true;
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            base.ResumeLayout(false);
        }

        #endregion
    }
}

